require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const mongoose = require('mongoose');
const Pesticide = require('../models/Pesticide');

const data = [
  // ─── APPLE ────────────────────────────────────────────────
  {
    class_name: 'Apple Scab (Apple)',
    crop: 'Apple',
    disease: 'Apple Scab',
    is_healthy: false,
    pesticide: {
      name: 'Captan 50 WP',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2g / 1L',
      safety: 'Wear gloves and mask. Avoid inhaling spray mist.',
      notes: 'Apply at bud break and continue through petal fall. Remove fallen leaves to reduce inoculum.',
    },
  },
  {
    class_name: 'Black Rot (Apple)',
    crop: 'Apple',
    disease: 'Black Rot',
    is_healthy: false,
    pesticide: {
      name: 'Thiophanate-methyl',
      dosage: '1.5g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '1.5g / 1L',
      safety: 'Avoid skin contact. Use in well-ventilated conditions.',
      notes: 'Prune and destroy infected branches. Avoid wounding fruit during harvest.',
    },
  },
  {
    class_name: 'Cedar Apple Rust (Apple)',
    crop: 'Apple',
    disease: 'Cedar Apple Rust',
    is_healthy: false,
    pesticide: {
      name: 'Myclobutanil',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 7-10 days',
      water_ratio: '1ml / 1L',
      safety: 'Wear protective clothing. Keep away from water bodies.',
      notes: 'Begin spraying at pink bud stage. Remove nearby juniper hosts if possible.',
    },
  },
  {
    class_name: 'Healthy (Apple)',
    crop: 'Apple',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Crop is healthy. Maintain normal irrigation and structural nutrient balances.',
    },
  },

  // ─── CORN ─────────────────────────────────────────────────
  {
    class_name: 'Blight (Corn)',
    crop: 'Corn',
    disease: 'Blight',
    is_healthy: false,
    pesticide: {
      name: 'Azoxystrobin / Pyraclostrobin',
      dosage: '1.2ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1.2ml / 1L',
      safety: 'Wear protective clothing and face shields during application.',
      notes: 'Apply proactively when ambient humidity levels are consistently high.',
    },
  },
  {
    class_name: 'Common Rust (Corn)',
    crop: 'Corn',
    disease: 'Common Rust',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 10-14 days',
      water_ratio: '1ml / 1L',
      safety: 'Wear gloves and eye protection.',
      notes: 'Apply early when pustules first appear on leaf clusters.',
    },
  },
  {
    class_name: 'Gray Leaf Spot (Corn)',
    crop: 'Corn',
    disease: 'Gray Leaf Spot',
    is_healthy: false,
    pesticide: {
      name: 'Mancozeb',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '2g / 1L',
      safety: 'Avoid inhaling spray. Use in calm wind conditions.',
      notes: 'Scout low-canopy layers regularly. Clear remaining structural crop debris after extraction.',
    },
  },
  {
    class_name: 'Northern Blight (Corn)',
    crop: 'Corn',
    disease: 'Northern Blight',
    is_healthy: false,
    pesticide: {
      name: 'Fluxapyroxad + Pyraclostrobin',
      dosage: '1.5ml per litre of water',
      spray_interval: 'Every 10-14 days',
      water_ratio: '1.5ml / 1L',
      safety: 'Wear chemical-resistant gloves and long sleeves.',
      notes: 'Focus spray passes on early leaf lesion centers to avoid total field dispersion.',
    },
  },
  {
    class_name: 'Healthy (Corn)',
    crop: 'Corn',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Crop is in prime condition.',
    },
  },

  // ─── COTTON ───────────────────────────────────────────────
  {
    class_name: 'Aphids (Cotton)',
    crop: 'Cotton',
    disease: 'Aphids',
    is_healthy: false,
    pesticide: {
      name: 'Imidacloprid',
      dosage: '0.5ml per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '0.5ml / 1L',
      safety: 'Avoid skin contact. Wash hands thoroughly after use.',
      notes: 'Monitor undersides of leaves. Maintain natural predators like ladybirds.',
    },
  },
  {
    class_name: 'Bacterial Blight (Cotton)',
    crop: 'Cotton',
    disease: 'Bacterial Blight',
    is_healthy: false,
    pesticide: {
      name: 'Copper Hydroxide',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2g / 1L',
      safety: 'Wear gloves. Avoid spraying in windy environments.',
      notes: 'Avoid using overhead sprinkle irrigation styles to limit wet canopy friction.',
    },
  },
  {
    class_name: 'Powdery Mildew (Cotton)',
    crop: 'Cotton',
    disease: 'Powdery Mildew',
    is_healthy: false,
    pesticide: {
      name: 'Hexaconazole',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 10-14 days',
      water_ratio: '1ml / 1L',
      safety: 'Wear protective clothing. Avoid contact with eyes.',
      notes: 'Apply at first sign of white structural coating on leaf structures.',
    },
  },
  {
    class_name: 'Target Spot (Cotton)',
    crop: 'Cotton',
    disease: 'Target Spot',
    is_healthy: false,
    pesticide: {
      name: 'Chlorothalonil',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2g / 1L',
      safety: 'Wear gloves and mask. Avoid spraying near open water vectors.',
      notes: 'Extract heavily infected low leaves. Apply strictly during low-sun hours.',
    },
  },
  {
    class_name: 'Healthy (Cotton)',
    crop: 'Cotton',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Cotton structures displaying clean vascular layout.',
    },
  },

  // ─── GRAPE ────────────────────────────────────────────────
  {
    class_name: 'Black Rot (Grape)',
    crop: 'Grape',
    disease: 'Black Rot',
    is_healthy: false,
    pesticide: {
      name: 'Myclobutanil',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 7-10 days',
      water_ratio: '1ml / 1L',
      safety: 'Wear full protective gear. Avoid inhalation.',
      notes: 'Remove mummified fruit and infected canes from the vineyard base.',
    },
  },
  {
    class_name: 'Esca (Grape)',
    crop: 'Grape',
    disease: 'Esca',
    is_healthy: false,
    pesticide: {
      name: 'No effective chemical cure',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'Remove and destroy infected wood layers promptly.',
      notes: 'Prune strictly during dry periods and seal open cane wounds manually.',
    },
  },
  {
    class_name: 'Leaf Blight (Grape)',
    crop: 'Grape',
    disease: 'Leaf Blight',
    is_healthy: false,
    pesticide: {
      name: 'Mancozeb',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '2g / 1L',
      safety: 'Do not inhale spray mist. Wear protective safety gloves.',
      notes: 'Clear the vineyard floor of damp organic materials.',
    },
  },
  {
    class_name: 'Healthy (Grape)',
    crop: 'Grape',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Vines in optimal metabolic health.',
    },
  },

  // ─── MANGO ────────────────────────────────────────────────
  {
    class_name: 'Anthracnose (Mango)',
    crop: 'Mango',
    disease: 'Anthracnose',
    is_healthy: false,
    pesticide: {
      name: 'Carbendazim',
      dosage: '1g per litre of water',
      spray_interval: 'Every 10-14 days',
      water_ratio: '1g / 1L',
      safety: 'Wear gloves and mask. Avoid contact with skin.',
      notes: 'Run treatments during flowering and initial fruit setting stages.',
    },
  },
  {
    class_name: 'Bacterial Canker (Mango)',
    crop: 'Mango',
    disease: 'Bacterial Canker',
    is_healthy: false,
    pesticide: {
      name: 'Copper Hydroxide',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '2g / 1L',
      safety: 'Wear protective gear. Wash hands thoroughly after execution.',
      notes: 'Prune damaged structural elements and seal surfaces with premium Bordeaux paste.',
    },
  },
  {
    class_name: 'Cutting Weevil (Mango)',
    crop: 'Mango',
    disease: 'Cutting Weevil',
    is_healthy: false,
    pesticide: {
      name: 'Alpha-cypermethrin',
      dosage: '1.5ml per litre of water',
      spray_interval: 'Every 15 days',
      water_ratio: '1.5ml / 1L',
      safety: 'Toxic — wear protective respirator and long clothes.',
      notes: 'Spray canopy thoroughly during new leaf flush to deter adult activity.',
    },
  },
  {
    class_name: 'Die Back (Mango)',
    crop: 'Mango',
    disease: 'Die Back',
    is_healthy: false,
    pesticide: {
      name: 'Thiophanate-methyl',
      dosage: '1.5g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '1.5g / 1L',
      safety: 'Wear thick gloves. Avoid inhaling fine aerosol mist.',
      notes: 'Prune structural wood branches clean 5cm below visible necrotic areas.',
    },
  },
  {
    class_name: 'Gall Midge (Mango)',
    crop: 'Mango',
    disease: 'Gall Midge',
    is_healthy: false,
    pesticide: {
      name: 'Dimethoate',
      dosage: '2ml per litre of water',
      spray_interval: 'Every 10 days during flushing',
      water_ratio: '2ml / 1L',
      safety: 'Avoid spraying during bloom periods to preserve local bee networks.',
      notes: 'Collect and bury deformed vegetative tissues immediately.',
    },
  },
  {
    class_name: 'Powdery Mildew (Mango)',
    crop: 'Mango',
    disease: 'Powdery Mildew',
    is_healthy: false,
    pesticide: {
      name: 'Wettable Sulfur',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10-14 days',
      water_ratio: '2g / 1L',
      safety: 'Do not distribute solution when ambient field climate exceeds 35°C.',
      notes: 'Crucial protective step during early panicle extensions.',
    },
  },
  {
    class_name: 'Sooty Mould (Mango)',
    crop: 'Mango',
    disease: 'Sooty Mould',
    is_healthy: false,
    pesticide: {
      name: 'Starch solution + Imidacloprid',
      dosage: '0.5ml Imidacloprid per litre',
      spray_interval: 'Every 14 days',
      water_ratio: '0.5ml / 1L',
      safety: 'Wear protective safety glasses.',
      notes: 'The mold consumes insect honeydew. Eradicate scaling mealybugs and aphids first.',
    },
  },
  {
    class_name: 'Healthy (Mango)',
    crop: 'Mango',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Mango grove exhibits stellar growth metrics.',
    },
  },

  // ─── POTATO ───────────────────────────────────────────────
  {
    class_name: 'Early Blight (Potato)',
    crop: 'Potato',
    disease: 'Early Blight',
    is_healthy: false,
    pesticide: {
      name: 'Mancozeb 75% WP',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '2g / 1L',
      safety: 'Avoid breathing dust when mixing. Use waterproof safety gloves.',
      notes: 'Initiate spraying as soon as lower foliage spots emerge.',
    },
  },
  {
    class_name: 'Late Blight (Potato)',
    crop: 'Potato',
    disease: 'Late Blight',
    is_healthy: false,
    pesticide: {
      name: 'Cymoxanil + Mancozeb',
      dosage: '2.5g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2.5g / 1L',
      safety: 'High-tier mask mandatory. Avoid field entry for 24 hours after treatment.',
      notes: 'Highly destructive. Hill up dense clean soil rows around bases to insulate root tubers.',
    },
  },
  {
    class_name: 'Healthy (Potato)',
    crop: 'Potato',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Potato crops showing perfect root-to-leaf vitality.',
    },
  },

  // ─── RICE ─────────────────────────────────────────────────
  {
    class_name: 'Bacterial Blight (Rice)',
    crop: 'Rice',
    disease: 'Bacterial Blight',
    is_healthy: false,
    pesticide: {
      name: 'Streptomycin Sulfate + Tetracycline Hydrochloride',
      dosage: '0.15g per litre of water',
      spray_interval: 'Every 7-10 days',
      water_ratio: '0.15g / 1L',
      safety: 'Wear a respirator mask and full rubber safety gear.',
      notes: 'Drain fields temporarily if infection starts multiplying uncontrollably.',
    },
  },
  {
    class_name: 'Brown Spot (Rice)',
    crop: 'Rice',
    disease: 'Brown Spot',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1ml / 1L',
      safety: 'Keep away from active freshwater systems or residential spaces.',
      notes: 'Apply during late tillering steps. Ensure soils have adequate potassium values.',
    },
  },
  {
    class_name: 'Healthy (Rice)',
    crop: 'Rice',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Paddy displays superb chlorophyll index readings.',
    },
  },
  {
    class_name: 'Hispa (Rice)',
    crop: 'Rice',
    disease: 'Hispa',
    is_healthy: false,
    pesticide: {
      name: 'Chlorpyrifos 20% EC',
      dosage: '2ml per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '2ml / 1L',
      safety: 'Extremely concentrated. Do not store near grain houses.',
      notes: 'Manually clip off damaged overarching leaf tips before launching treatment.',
    },
  },
  {
    class_name: 'Leaf Blast (Rice)',
    crop: 'Rice',
    disease: 'Leaf Blast',
    is_healthy: false,
    pesticide: {
      name: 'Tricyclazole',
      dosage: '0.6g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '0.6g / 1L',
      safety: 'Minimize dermal contact risks. Wear rubber boots.',
      notes: 'Act immediately when spindle-shaped lesions present on central leaves.',
    },
  },
  {
    class_name: 'Leaf Scald (Rice)',
    crop: 'Rice',
    disease: 'Leaf Scald',
    is_healthy: false,
    pesticide: {
      name: 'Carbendazim + Mancozeb',
      dosage: '2g per litre of water',
      spray_interval: 'Every 12 days',
      water_ratio: '2g / 1L',
      safety: 'Avoid spraying during overhead noon wind gusts.',
      notes: 'Optimize nitrogen input pacing to prevent weak vegetative walls.',
    },
  },
  {
    class_name: 'Sheath Blight (Rice)',
    crop: 'Rice',
    disease: 'Sheath Blight',
    is_healthy: false,
    pesticide: {
      name: 'Hexaconazole 5% EC',
      dosage: '2ml per litre of water',
      spray_interval: 'Every 10-14 days',
      water_ratio: '2ml / 1L',
      safety: 'Wash chemical spray kits thoroughly away from household channels.',
      notes: 'Direct spray focus onto lower leaf sheath lines near the waterline.',
    },
  },

  // ─── SUGARCANE ────────────────────────────────────────────
  {
    class_name: 'Bacterial Blight (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Bacterial Blight',
    is_healthy: false,
    pesticide: {
      name: 'Copper Oxychloride',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '2g / 1L',
      safety: 'Wear protective technical overalls. Wash face clean after application.',
      notes: 'Clear away out-of-season residual stubble post-harvest to disrupt pathogen loops.',
    },
  },
  {
    class_name: 'Banded Chlorosis (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Banded Chlorosis',
    is_healthy: false,
    pesticide: {
      name: 'Foliar Micronutrient Mixture + Carbendazim',
      dosage: '1g fungicide per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1g / 1L',
      safety: 'Standard personal protective equipment required.',
      notes: 'Often linked with severe temperature fluctuations; boost structural resilience with balanced trace elements.',
    },
  },
  {
    class_name: 'Brown Rust (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Brown Rust',
    is_healthy: false,
    pesticide: {
      name: 'Tebuconazole',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1ml / 1L',
      safety: 'Keep livestock away from treated perimeter zones for 14 days.',
      notes: 'Apply immediately when orange-brown linear pustules appear on lower surfaces.',
    },
  },
  {
    class_name: 'Brown Spot (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Brown Spot',
    is_healthy: false,
    pesticide: {
      name: 'Mancozeb',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10-12 days',
      water_ratio: '2g / 1L',
      safety: 'Wear gloves and clean eye protection mirrors.',
      notes: 'Ensure proper field drainage setups to minimize microclimate moisture trap zones.',
    },
  },
  {
    class_name: 'Grassy Shoot (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Grassy Shoot',
    is_healthy: false,
    pesticide: {
      name: 'No effective chemical cure (Vector management via Malathion)',
      dosage: '2ml per litre of water',
      spray_interval: 'Every 15 days to suppress insect vectors',
      water_ratio: '2ml / 1L',
      safety: 'Handle concentrate material using full face mask protections.',
      notes: 'Uproot infected dwarf cane clusters immediately. Treat planting setts with hot water.',
    },
  },
  {
    class_name: 'Healthy (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Stalk systems show robust fibrous metric indicators.',
    },
  },
  {
    class_name: 'Mosaic (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Mosaic',
    is_healthy: false,
    pesticide: {
      name: 'Thiamethoxam (Vector Control)',
      dosage: '0.5g per litre of water',
      spray_interval: 'Every 12 days',
      water_ratio: '0.5g / 1L',
      safety: 'Avoid direct inhalation of atomized vapor cloud layers.',
      notes: 'Eradicates aphid networks transmitting viral strains. Routinely pull out affected items.',
    },
  },
  {
    class_name: 'Pokkah Boeng (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Pokkah Boeng',
    is_healthy: false,
    pesticide: {
      name: 'Copper Oxychloride 50% WP',
      dosage: '2.5g per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '2.5g / 1L',
      safety: 'Ensure proper workspace skin coverage via heavy rubber gloves.',
      notes: 'Direct misting into the top structural whorl where leaf distortion gathers.',
    },
  },
  {
    class_name: 'Red Rot (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Red Rot',
    is_healthy: false,
    pesticide: {
      name: 'Thiophanate-methyl (Sett treatment focus)',
      dosage: '1.5g per litre of water',
      spray_interval: 'Immerse seed pieces prior to field setting',
      water_ratio: '1.5g / 1L',
      safety: 'Use protective gear during active seed fluid soaking operations.',
      notes: 'Submerge setts for 20 minutes minimum. Ensure complete elimination of waterlogging fields.',
    },
  },
  {
    class_name: 'Rust (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Rust',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1ml / 1L',
      safety: 'Wear protective technical overalls. Avoid contact with eyes.',
      notes: 'Deploy early during pustule initialization to secure structural stalks.',
    },
  },
  {
    class_name: 'Sett Rot (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Sett Rot',
    is_healthy: false,
    pesticide: {
      name: 'Carbendazim 50% WP',
      dosage: '1g per litre of water',
      spray_interval: 'Pre-planting deep soak',
      water_ratio: '1g / 1L',
      safety: 'Always mix chemical substances in outdoor locations.',
      notes: 'Protects open cut cane surfaces against soil-borne fungal entry.',
    },
  },
  {
    class_name: 'Smut (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Smut',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole (Sett dip and canopy spray)',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days upon whip detection',
      water_ratio: '1ml / 1L',
      safety: 'Wear clear protective glasses and long canvas pants.',
      notes: 'Carefully bag and remove elongated black fungal whips to stop spore cloud dispersion.',
    },
  },
  {
    class_name: 'Viral Disease (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Viral Disease',
    is_healthy: false,
    pesticide: {
      name: 'Acetamiprid (Insect Vector Suppressor)',
      dosage: '0.4g per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '0.4g / 1L',
      safety: 'Wash contaminated clothes separately from domestic loads.',
      notes: 'Target sucking insect populations to arrest secondary transmission pathways.',
    },
  },
  {
    class_name: 'Yellow Leaf (Sugarcane)',
    crop: 'Sugarcane',
    disease: 'Yellow Leaf',
    is_healthy: false,
    pesticide: {
      name: 'Imidacloprid 17.8% SL',
      dosage: '0.5ml per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '0.5ml / 1L',
      safety: 'Keep far away from children. Secure storage locker protocols.',
      notes: 'Neutralizes sugarcane aphid colonies tracking virus variants across midrib lines.',
    },
  },

  // ─── TOMATO ───────────────────────────────────────────────
  {
    class_name: 'Bacterial Spot (Tomato)',
    crop: 'Tomato',
    disease: 'Bacterial Spot',
    is_healthy: false,
    pesticide: {
      name: 'Copper Hydroxide + Mancozeb',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2g / 1L',
      safety: 'Wear thick protective gloves. Wash equipment thoroughly after deployment.',
      notes: 'Apply ahead of rain blocks. Avoid foliage trimming during wet weather.',
    },
  },
  {
    class_name: 'Early Blight (Tomato)',
    crop: 'Tomato',
    disease: 'Early Blight',
    is_healthy: false,
    pesticide: {
      name: 'Copper Oxychloride',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2g / 1L',
      safety: 'Wear gloves and mask during distribution.',
      notes: 'Prune out old low ground-facing leaves before starting chemical distribution runs.',
    },
  },
  {
    class_name: 'Late Blight (Tomato)',
    crop: 'Tomato',
    disease: 'Late Blight',
    is_healthy: false,
    pesticide: {
      name: 'Metalaxyl + Mancozeb',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2g / 1L',
      safety: 'Wear full protective technical clothing suites. Keep animals secure.',
      notes: 'Highly critical condition. Immediately run applications when cold damp night shifts occur.',
    },
  },
  {
    class_name: 'Leaf Mold (Tomato)',
    crop: 'Tomato',
    disease: 'Leaf Mold',
    is_healthy: false,
    pesticide: {
      name: 'Mancozeb',
      dosage: '2.5g per litre of water',
      spray_interval: 'Every 7-10 days',
      water_ratio: '2.5g / 1L',
      safety: 'Use solid technical gear cloth sets. Do not inhale vapor zones.',
      notes: 'Optimize internal greenhouse circulation configurations to keep baseline levels crisp.',
    },
  },
  {
    class_name: 'Mosaic Virus (Tomato)',
    crop: 'Tomato',
    disease: 'Mosaic Virus',
    is_healthy: false,
    pesticide: {
      name: 'No chemical treatment exists',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'Safely discard infected vegetation units using enclosed methods.',
      notes: 'Sterilize field scissors with isopropyl alcohol alternatives regularly.',
    },
  },
  {
    class_name: 'Powdery Mildew (Tomato)',
    crop: 'Tomato',
    disease: 'Powdery Mildew',
    is_healthy: false,
    pesticide: {
      name: 'Azoxystrobin',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '1ml / 1L',
      safety: 'Wear gloves. Avoid contact with eyes.',
      notes: 'Ensure clean canopy visibility to intercept fuzzy gray spots early.',
    },
  },
  {
    class_name: 'Septoria Leaf Spot (Tomato)',
    crop: 'Tomato',
    disease: 'Septoria Leaf Spot',
    is_healthy: false,
    pesticide: {
      name: 'Chlorothalonil',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7-10 days',
      water_ratio: '2g / 1L',
      safety: 'Avoid skin and eye touch regions. Use in open configurations.',
      notes: 'Prune away lowest infected leaf clusters to eliminate ground splash tracking.',
    },
  },
  {
    class_name: 'Spider Mites (Tomato)',
    crop: 'Tomato',
    disease: 'Spider Mites',
    is_healthy: false,
    pesticide: {
      name: 'Abamectin',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 5-7 days',
      water_ratio: '1ml / 1L',
      safety: 'Highly potent agent. Use heavy industrial gloves during mix cycles.',
      notes: 'Direct pressure streams below leaves where web matrices congregate.',
    },
  },
  {
    class_name: 'Target Spot (Tomato)',
    crop: 'Tomato',
    disease: 'Target Spot',
    is_healthy: false,
    pesticide: {
      name: 'Chlorothalonil',
      dosage: '2g per litre of water',
      spray_interval: 'Every 7 days',
      water_ratio: '2g / 1L',
      safety: 'Wear technical masks. Keep fluid away from aquaculture streams.',
      notes: 'Distribute early morning or post-sunset intervals for optimal absorption.',
    },
  },
  {
    class_name: 'Yellow Leaf Curl Virus (Tomato)',
    crop: 'Tomato',
    disease: 'Yellow Leaf Curl Virus',
    is_healthy: false,
    pesticide: {
      name: 'Imidacloprid',
      dosage: '0.5ml per litre of water',
      spray_interval: 'Every 10 days',
      water_ratio: '0.5ml / 1L',
      safety: 'Wash hands clean with grease-stripping soaps post-use.',
      notes: 'Suppresses silverleaf whitefly populations carrying the viral code.',
    },
  },
  {
    class_name: 'Healthy (Tomato)',
    crop: 'Tomato',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Tomato plants displaying rich, sturdy vascular branch structures.',
    },
  },

  // ─── WHEAT ────────────────────────────────────────────────
  {
    class_name: 'Aphids (Wheat)',
    crop: 'Wheat',
    disease: 'Aphids',
    is_healthy: false,
    pesticide: {
      name: 'Dimethoate 40% EC',
      dosage: '1.5ml per litre of water',
      spray_interval: 'Single application at threshold',
      water_ratio: '1.5ml / 1L',
      safety: 'Wear full boots, mask, and chemical gloves.',
      notes: 'Treat if aphid counts exceed 5 per ear during head emergence steps.',
    },
  },
  {
    class_name: 'Black Rust (Wheat)',
    crop: 'Wheat',
    disease: 'Black Rust',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole 25% EC',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days if severe',
      water_ratio: '1ml / 1L',
      safety: 'Avoid spraying near domestic water wells or livestock lines.',
      notes: 'Also known as stem rust. Focus application heavily on lower leaf shafts.',
    },
  },
  {
    class_name: 'Blast (Wheat)',
    crop: 'Wheat',
    disease: 'Blast',
    is_healthy: false,
    pesticide: {
      name: 'Tebuconazole + Trifloxystrobin',
      dosage: '1.2ml per litre of water',
      spray_interval: 'Every 10-12 days',
      water_ratio: '1.2ml / 1L',
      safety: 'Wear face shield and protective clothes. Do not inhale vapor.',
      notes: 'Extremely time-sensitive spike disease; treat at early heading stages.',
    },
  },
  {
    class_name: 'Brown Rust (Wheat)',
    crop: 'Wheat',
    disease: 'Brown Rust',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1ml / 1L',
      safety: 'Use protective heavy gloves and standard face shields.',
      notes: 'Target upper flag leaves carefully to preserve overall grain fill capacity.',
    },
  },
  {
    class_name: 'Common Root Rot (Wheat)',
    crop: 'Wheat',
    disease: 'Common Root Rot',
    is_healthy: false,
    pesticide: {
      name: 'Carboxin + Thiram (Seed dressing application)',
      dosage: '2g per kg of seed grain',
      spray_interval: 'Single pre-sowing seed treatment coating',
      water_ratio: 'Slurry mix format',
      safety: 'Handle raw powder strictly wearing particle masks outdoors.',
      notes: 'Soil-borne issue. Ensure deep tillage practices and systemic crop rotations.',
    },
  },
  {
    class_name: 'Fusarium Head Blight (Wheat)',
    crop: 'Wheat',
    disease: 'Fusarium Head Blight',
    is_healthy: false,
    pesticide: {
      name: 'Prothioconazole',
      dosage: '1.5ml per litre of water',
      spray_interval: 'Single targeted run at early flowering split',
      water_ratio: '1.5ml / 1L',
      safety: 'Strict 30-day pre-harvest interval mandatory.',
      notes: 'Deploy at early anthemia (flowering) phase to maximize grain safety.',
    },
  },
  {
    class_name: 'Leaf Blight (Wheat)',
    crop: 'Wheat',
    disease: 'Leaf Blight',
    is_healthy: false,
    pesticide: {
      name: 'Zineb 75% WP',
      dosage: '2g per litre of water',
      spray_interval: 'Every 10-14 days',
      water_ratio: '2g / 1L',
      safety: 'Avoid breathing dust. Wash safety gear immediately after use.',
      notes: 'Monitor fields for dark brown oval lesions during warm, overcast spells.',
    },
  },
  {
    class_name: 'Mites (Wheat)',
    crop: 'Wheat',
    disease: 'Mites',
    is_healthy: false,
    pesticide: {
      name: 'Spiromesifen 22.9% SC',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days if population persists',
      water_ratio: '1ml / 1L',
      safety: 'Toxic to aquatic organisms. Prevent field drainage runoffs.',
      notes: 'Look for speckling patterns or silvery leaf sheaths under dry weather blocks.',
    },
  },
  {
    class_name: 'Powdery Mildew (Wheat)',
    crop: 'Wheat',
    disease: 'Powdery Mildew',
    is_healthy: false,
    pesticide: {
      name: 'Tebuconazole 250 EC',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1ml / 1L',
      safety: 'Wear appropriate technical respiratory protectors.',
      notes: 'Treat promptly if white cotton-like tufts spread onto upper leaf sections.',
    },
  },
  {
    class_name: 'Septoria (Wheat)',
    crop: 'Wheat',
    disease: 'Septoria',
    is_healthy: false,
    pesticide: {
      name: 'Epoxiconazole',
      dosage: '1.2ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1.2ml / 1L',
      safety: 'Wear long chemical-resistant boots and overalls.',
      notes: 'Protects critical flag leaf areas from developing dense blotches.',
    },
  },
  {
    class_name: 'Smut (Wheat)',
    crop: 'Wheat',
    disease: 'Smut',
    is_healthy: false,
    pesticide: {
      name: 'Tebuconazole 2% DS (Seed treatment format)',
      dosage: '2g per kg of seed grain',
      spray_interval: 'Single treatment prior to planting operations',
      water_ratio: 'Dry/Slurry seed dressing mix',
      safety: 'Never use treated seed grain for direct food consumption channels.',
      notes: 'Systemic seed issue. Total avoidance relies on clean seedling coatings.',
    },
  },
  {
    class_name: 'Stem Fly (Wheat)',
    crop: 'Wheat',
    disease: 'Stem Fly',
    is_healthy: false,
    pesticide: {
      name: 'Fipronil 5% SC',
      dosage: '1.5ml per litre of water',
      spray_interval: 'Every 12 days at early vegetative stages',
      water_ratio: '1.5ml / 1L',
      safety: 'Wear protective clothing and heavy-duty nitrile gloves.',
      notes: 'Look for "dead hearts" in seedlings. Apply early to catch boring larvae.',
    },
  },
  {
    class_name: 'Tan Spot (Wheat)',
    crop: 'Wheat',
    disease: 'Tan Spot',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole + Azoxystrobin',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days',
      water_ratio: '1ml / 1L',
      safety: 'Ensure proper face mask coverage during mixing passes.',
      notes: 'Manage field stubble decay rates carefully to eliminate fungal host carryover.',
    },
  },
  {
    class_name: 'Yellow Rust (Wheat)',
    crop: 'Wheat',
    disease: 'Yellow Rust',
    is_healthy: false,
    pesticide: {
      name: 'Propiconazole 25% EC',
      dosage: '1ml per litre of water',
      spray_interval: 'Every 14 days if yellow stripes expand',
      water_ratio: '1ml / 1L',
      safety: 'Wash skin thoroughly with soap if accidental contact occurs.',
      notes: 'Spreads rapidly in cool, wet environments. Treat early before full yellow stripe development.',
    },
  },
  {
    class_name: 'Healthy (Wheat)',
    crop: 'Wheat',
    disease: 'Healthy',
    is_healthy: true,
    pesticide: {
      name: 'None',
      dosage: 'N/A',
      spray_interval: 'N/A',
      water_ratio: 'N/A',
      safety: 'N/A',
      notes: 'Wheat crop canopy is healthy. Continue tracking soil moisture inputs.',
    },
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected successfully');

    await Pesticide.deleteMany({});
    console.log('Cleared existing pesticide data from collection');

    await Pesticide.insertMany(data);
    console.log(`Seeded ${data.length} pesticide records into MongoDB`);

    mongoose.disconnect();
    console.log('Database connection cleanly terminated');
  } catch (err) {
    console.error('Seeding failed:', err.message);
    process.exit(1);
  }
};

seed();